language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

before_script:
    mkdir tests/data & composer install -n

script:
    - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests ; fi
    - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then ./vendor/bin/phpunit --configuration tests/phpunit.xml tests ; fi

after_script:
    - CODECLIMATE_REPO_TOKEN=762aad35dec31cb31a0a152e455c57d6b1474f5d078a2504d4ad83cd5e515cca
    - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then ./vendor/bin/test-reporter ; fi