language: php

php:
    - 5.6
    - 7.2

before_script:
    mkdir tests/data & composer install -n

script:
    - phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
    - CODECLIMATE_REPO_TOKEN=762aad35dec31cb31a0a152e455c57d6b1474f5d078a2504d4ad83cd5e515cca
    - ./vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: 762aad35dec31cb31a0a152e455c57d6b1474f5d078a2504d4ad83cd5e515cca